<a href="https://colab.research.google.com/github/sanjuvc01/sanjuvc01/blob/main/Python_exce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
city_name = input("Enter the city name: ")
print("city Name: ",(city_name))


Enter the city name: kundapura
city Name:  kundapura


In [ ]:
temprature=25
print(f"Temprature:{temprature}C")

Temprature:25C


In [ ]:
current_footprint = 3.75
print(f"The Carbon footprint: {current_footprint}kg CO2")

The Carbon footprint: 3.75kg CO2


In [ ]:
carbon_footprint=300
is_sustainability= carbon_footprint<400
print(f"Is The City Is Sustainable {is_sustainability}")

Is The City Is Sustainable True


In [ ]:
city_data={
    "Name":"city A",
    "Temperature":25,
    "Carbon Footprint":300,
    "Is Sustainable":False
}
print(f"City Data Is :{city_data}")

City Data Is :{'Name': 'city A', 'Temperature': 25, 'Carbon Footprint': 300, 'Is Sustainable': False}


In [ ]:
city_name, temperature ,carbon_footprint="City B",30,350.50
print(f"City Name:{city_name} \nTemperature:{temperature}C \nCarbon Footprint:{carbon_footprint}kg CO2")

City Name:City B 
Temperature:30C 
Carbon Footprint:350.5kg CO2


In [ ]:
a=5
print(f"Type A  {type(a)}")
b=5.0
print(f"Type B  {type(b)}")
c=2+3j
print(f"Type C  {type(c)}")
d=True
print(f"Type D  {type(d)}")
e="Hello"
print(f"Type E  {type(e)}")

Type A  <class 'int'>
Type B  <class 'float'>
Type C  <class 'complex'>
Type D  <class 'bool'>
Type E  <class 'str'>


In [ ]:
num=input("Enter A Number:")
print(f"You Entered :{num}")
print(f"Type of Number :{type(num)}")

Enter A Number:1
You Entered :1
Type of Number :<class 'str'>


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(31):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30


In [ ]:
for i in range(2,7):
  print(i)

2
3
4
5
6


In [ ]:
for i in range(11,28
              ):
  print(i)

11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [ ]:
for i in range(1,10,2):
  print(i)

1
3
5
7
9


In [ ]:
for i in range(3,31,3):
  print(i)

3
6
9
12
15
18
21
24
27
30


In [ ]:
climate_data=[
    {"city":"city A", "temperature":25, "carbon_footprint":500},
      {"city":"city B", "temperature":30, "carbon_footprint":350},
      {"city":"city C", "temperature":22, "carbon_footprint":600},
      {"city":"city D", "temperature":15, "carbon_footprint":200},
      {"city":"city E", "temperature":28, "carbon_footprint":450}
]
high_temp_threshold = 26
high_temp_cities=[city for city in climate_data if city["temperature"]>high_temp_threshold]
print("Cities With High Temperature:")
for city in high_temp_cities:
  print(f"{city['city']} - {city['temperature']}C")


Cities With High Temperature:
city B - 30C
city E - 28C


In [ ]:
total_carbon = 0
for city in climate_data:
  total_carbon += city["carbon_footprint"]
average_carbon_footprint = total_carbon / len(climate_data)
print(f"Average Carbon Footprint:{average_carbon_footprint:.2f}kg CO2")

Average Carbon Footprint:420.00kg CO2


In [ ]:
sustainability_threshold = 400
sustainable_cities = list(filter(lambda city: city ["carbon_footprint"]< sustainability_threshold,climate_data))
print("\nSustainable Cities (carbon footprint < 400kg CO2):")
for city in sustainable_cities:
  print(f"{city['city']} - {city['carbon_footprint']}kg CO2")


Sustainable Cities (carbon footprint < 400kg CO2):
city B - 350kg CO2
city D - 200kg CO2


In [ ]:
highest_footprint_city = max(climate_data, key=lambda city: city ["carbon_footprint"])
print(f"\nCity with the highest carbon footprint:")
print(f" {highest_footprint_city['city']} - {highest_footprint_city['carbon_footprint']} kg CO2")


City with the highest carbon footprint:
 city C - 600 kg CO2


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Iris.csv")

In [ ]:
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


In [9]:
df.head(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa


In [12]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica


In [13]:
df.shape

(150, 6)

In [15]:
df.describe()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,5.843333,3.054000,3.758667,1.198667
std,43.445368,0.828066,0.433594,1.764420,0.763161
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,38.250000,5.100000,2.800000,1.600000,0.300000
50%,75.500000,5.800000,3.000000,4.350000,1.300000
75%,112.750000,6.400000,3.300000,5.100000,1.800000
max,150.000000,7.900000,4.400000,6.900000,2.500000


In [19]:
df["Species"]

,Species
0,Iris-setosa
1,Iris-setosa
2,Iris-setosa
3,Iris-setosa
4,Iris-setosa
...,...
145,Iris-virginica
146,Iris-virginica
147,Iris-virginica
148,Iris-virginica


In [26]:
df.loc[101]

,101
Id,102
SepalLengthCm,5.8
SepalWidthCm,2.7
PetalLengthCm,5.1
PetalWidthCm,1.9
Species,Iris-virginica


In [27]:
df.PetalLengthCm[101]

np.float64(5.1)

In [28]:
import numpy as np
a=np.array([0,1,2,3])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(len(a))

[0 1 2 3]
<class 'numpy.ndarray'>
1
(4,)
4


In [29]:
mylist=[[1,2,3],[4,5,6],[7,8,9]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.random.rand(4)

array([0.08936156, 0.04477839, 0.21429068, 0.56935371])

In [31]:
np.random.rand(4,4)

array([[0.72722046, 0.20094201, 0.98428947, 0.27880742],
       [0.89043057, 0.13639788, 0.52218002, 0.82586787],
       [0.38864492, 0.80235824, 0.28309403, 0.96018739],
       [0.32034695, 0.82982708, 0.93226646, 0.53055096]])

In [37]:
np.random.randn(4)

array([-0.64868284,  0.57492103, -0.51144494, -0.2123938 ])

In [34]:
np.random.rand(10)

array([0.89281085, 0.25973211, 0.30969388, 0.31852168, 0.58086935,
       0.92201851, 0.46831014, 0.63696564, 0.77593317, 0.37447261])

In [40]:
np.random.randn(10)

array([ 0.30975321, -0.57463034, -1.05548943, -0.36357005,  0.46042383,
        1.042962  ,  1.83073993, -0.72193639, -1.17197981,  0.20929766])

In [44]:
np.power(a,2)

array([0, 1, 4, 9])

In [49]:
np.sqrt(2)

np.float64(1.4142135623730951)

In [51]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
np.max(10)

np.int64(10)

In [71]:
import pandas as pd
import numpy as np
data={
    "Energy Source":["solar","wind","Hydropower","geothermal","biomass","nuclear"],
    "Energy Consumption(Mwh)":[1200,np.nan,2900,np.nan,2500,3200],
    "cost(million $) ":[200,400,np.nan,150,250,np.nan]
}
energy_df=pd.DataFrame(data)
print("original energy data with missing values:")
print(energy_df)


original energy data with missing values:
  Energy Source  Energy Consumption(Mwh)  cost(million $) 
0         solar                   1200.0             200.0
1          wind                      NaN             400.0
2    Hydropower                   2900.0               NaN
3    geothermal                      NaN             150.0
4       biomass                   2500.0             250.0
5       nuclear                   3200.0               NaN


In [73]:
energy_df.shape

(6, 3)